services:

  ccf-orchestrator:
    build:

      additional_contexts:
        - workspace_root=/

      dockerfile_inline: |
        FROM mcr.microsoft.com/devcontainers/base:latest

        USER root

        RUN apt-get update \
          && apt-get install -y --no-install-recommends \
              ca-certificates \
              curl \
          && rm -rf /var/lib/apt/lists/*

        RUN curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh" \
          | bash -s -- --version latest

        ENV _REMOTE_USER="root"
        RUN curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/main/src/azure-cli/install.sh" \
          | bash -s --

        # Install cleanroom Azure CLI extension
        RUN az extension add -y --allow-preview true \
          --source https://cleanroomazcli.blob.core.windows.net/azcli/cleanroom-1.0.0-py2.py3-none-any.whl

        # Copy main orchestrator script and workspace
        COPY orchestrate.sh /orchestrate.sh
        COPY --from=workspace_root $WORKSPACE /workspace

        CMD /orchestrate.sh
    env_file: .env
    privileged: true

    # Azure CLI credentials from host
    volumes:
      - ${HOME}/.azure/msal_token_cache.json:/root/.azure/msal_token_cache.json
      - ${HOME}/.azure/azureProfile.json:/root/.azure/azureProfile.json
      - ${HOME}/.azure/service_principal_entries.json:/root/.azure/service_principal_entries.json

    healthcheck:
      test: ["CMD", "test", "-f", "/health.json"]
      interval: 1s
      retries: 1200
