services:

  ccf-orchestrator:
    build:

      additional_contexts:
        - workspace_root=/

      dockerfile_inline: |
        FROM mcr.microsoft.com/devcontainers/base:latest

        USER root

        RUN apt-get update \
          && apt-get install -y --no-install-recommends \
              ca-certificates \
              curl \
          && rm -rf /var/lib/apt/lists/*

        RUN curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/main/src/docker-in-docker/install.sh" \
          | bash -s -- --version latest

        ENV _REMOTE_USER="root"
        RUN curl -fsSL "https://raw.githubusercontent.com/devcontainers/features/main/src/azure-cli/install.sh" \
          | bash -s --

        # Install cleanroom Azure CLI extension
        RUN az extension add -y --allow-preview true \
          --source https://cleanroomazcli.blob.core.windows.net/azcli/cleanroom-1.0.0-py2.py3-none-any.whl

        # Copy main orchestrator script and workspace
        COPY orchestrate.sh /orchestrate.sh
        COPY --from=workspace_root $WORKSPACE /workspace
    command: /orchestrate.sh
    env_file: .env
    privileged: true

    # Azure CLI credentials from host
    volumes:
      - ${HOME}/.azure/msal_token_cache.json:/root/.azure/msal_token_cache.json
      - ${HOME}/.azure/azureProfile.json:/root/.azure/azureProfile.json
      - ${HOME}/.azure/tokenCache.json:/root/.azure/tokenCache.json
      - ${HOME}/.azure/az.sess:/root/.azure/az.sess
      - ${HOME}/.azure/service_principal_entries.json:/root/.azure/service_principal_entries.json
      - ${HOME}/.azure/msal_http_cache.bin:/root/.azure/msal_http_cache.bin
      - ${HOME}/.azure/config:/root/.azure/config
      - ${HOME}/.azure/clouds.config:/root/.azure/clouds.config
      - ${HOME}/.azure/az.json:/root/.azure/az.json
      - ${HOME}/.azure/extensionCommandTree.json:/root/.azure/extensionCommandTree.json
      - ${HOME}/.azure/commandIndex.json:/root/.azure/commandIndex.json
      - ${HOME}/.azure/commands:/root/.azure/commands
      - ${HOME}/.azure/versionCheck.json:/root/.azure/versionCheck.json
      - ${HOME}/.azure/logs:/root/.azure/logs
      - ${HOME}/.azure/telemetry:/root/.azure/telemetry
      - ${HOME}/.azure/telemetry.txt:/root/.azure/telemetry.txt
      - ${HOME}/.azure/az_survey.json:/root/.azure/az_survey.json

    healthcheck:
      test: ["CMD", "test", "-f", "/health.json"]
      interval: 1s
      retries: 1200
