# Container in which CI testing is run
# Does incremental builds of the latest version of code from the base image
# Provides command which runs the tests and starts a webserver to serve the logs

FROM privacysandbox.azurecr.io/base:latest

ARG CCF_REV="main"
ARG KMS_REV="main"
ARG BIDDING_AUCTION_SERVERS_REV="azure-support"
ARG DATA_PLANE_SHARED_LIBRARIES_REV="azure-support"

RUN LINES_TO_COMMENT=$(grep -n "Cannot verify virtual attestation report if node is SEV-SNP" CCF/include/ccf/pal/attestation.h | cut -f1 -d:) && \
    sed -i "$((LINES_TO_COMMENT - 3)),$((LINES_TO_COMMENT + 1))s/\/\///" CCF/include/ccf/pal/attestation.h
RUN (cd CCF && git fetch && git checkout $CCF_REV)
RUN LINES_TO_COMMENT=$(grep -n "Cannot verify virtual attestation report if node is SEV-SNP" CCF/include/ccf/pal/attestation.h | cut -f1 -d:) && \
    sed -i "$((LINES_TO_COMMENT - 3)),$((LINES_TO_COMMENT + 1))s/^/\/\//" CCF/include/ccf/pal/attestation.h

RUN (cd Protected-Audiences && git fetch && git checkout $KMS_REV)
RUN (cd bidding-auction-servers && git fetch && git checkout $BIDDING_AUCTION_SERVERS_REV)
RUN (cd bidding-auction-servers/data-plane-shared-libraries && git fetch && git checkout $DATA_PLANE_SHARED_LIBRARIES_REV)

COPY Makefile ./Makefile
COPY scripts/ ./scripts

ARG BAZEL_CACHE
ENV BAZEL_CACHE_DEV=$BAZEL_CACHE

RUN make kms-build
RUN make ba-build
RUN make test-build

CMD echo "export UVM_SECURITY_CONTEXT_DIR=$UVM_SECURITY_CONTEXT_DIR" >> /root/.bashrc && \
    mkdir -p logs && touch logs/test_logs.txt && \
    (make integration-test > logs/test_logs.txt 2>&1 || true) && \
    cd logs && \
    python3 -m http.server 8001
