name: System Test

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      test_path:
        type: string
        description: "Path to pytest file/s"
      env:
        type: string
        description: The CCF service type to run KMS on
      use_akv:
        type: boolean
        description: Whether or not to store keys in AKV
  workflow_call:
    inputs:
      test_path:
        type: string
        description: "Path to pytest file/s"
      env:
        type: string
        description: The CCF service type to run KMS on
      use_akv:
        type: boolean
        description: Whether or not to store keys in AKV

jobs:

  test:
    name: ${{ inputs.test_path }} (${{ inputs.env }}, ${{ inputs.use_akv && 'akv' || 'local' }}_keys)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: pip install -r requirements.txt

      - name: Log into Azure
        uses: azure/login@v2
        with:
          # Use a managed identity to authenticate to Azure
          # Use properties such as client-id, tenant-id, and subscription-id in the secrets and vars
          # The managed identity should have a federated credential with subject identiier repo:<organization>/<repo>:pull_request
          # Use subject identifier repo:<organization>/<repo>:ref:refs/heads/<branch> for running manual CI's
          client-id: ${{ vars.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ vars.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Run System Tests
        env:
          TEST_ENVIRONMENT: ccf/${{ inputs.env }}
          USE_AKV: ${{ inputs.use_akv }}
        run: |
          pytest -sv \
            test/system-test/${{ inputs.test_path }}.py