name: Test Orchestrator

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:

  test-orchestrator:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ vars.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install Dependencies
        run: pip install -r scripts/ccf/az-cleanroom-aci/orchestrator/requirements.txt

      - name: Test Orchestrator
        run: pytest -sv scripts/ccf/az-cleanroom-aci/orchestrator/test/test.py

      - name: Print Orchestrator Logs
        if: always()
        run: docker compose -p orchestrator logs
