name: Test Orchestrator

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:

  test-orchestrator:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Orchestrator
        uses: devcontainers/ci@v0.3
        with:
          push: never
          configFile: scripts/ccf/az-cleanroom-aci/orchestrator/.devcontainer/devcontainer.json
          env:
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          runCmd: |
            az login --service-principal \
              --username $AZURE_CLIENT_ID \
              --password $AZURE_CLIENT_SECRET \
              --tenant $AZURE_TENANT_ID
            pytest -sv scripts/ccf/az-cleanroom-aci/orchestrator/test.py